name: Run CircleCI from label

on:
  pull_request:
    types: [ labeled ]

jobs:
  run-e2e-windows:
    if: ${{ github.event.label.name == 'run-e2e-windows' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Running e2e tests on Windows

  run-e2e-unix:
    if: ${{ github.event.label.name == 'run-e2e-unix' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Running e2e tests on Unix

  run-e2e:
    if: ${{ github.event.label.name == 'run-e2e' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Running e2e tests on Windows and Unix
